trigger:
  branches:
    include:
      - master

stages:
  - stage: Source
    displayName: 'Fetch source code'
    steps:
      - checkout: self

  - stage: Build
    displayName: 'Build application'
    dependsOn: Source
    steps:
      - task: UseNode@1
        inputs:
          version: '16.x'
      - script: |
          npm install
          npm run build
        displayName: 'Build app'