trigger:
  branches:
    include:
      - master

pool:
  name: 'MyMacAgentPool'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Difenter'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Start deploying to Blob Storage..."
      az storage blob upload-batch \
        --account-name $STORAGE_NAME \
        --destination '$web' \
        --source './dist' \
        --auth-mode key \
        --account-key $STORAGE_KEY
  env:
    STORAGE_NAME: $(STORAGEACCOUNTNAME)
    STORAGE_KEY: $(STORAGEKEY)
