trigger:
  branches:
    include:
      - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Use your Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'  # adjust to your build output folder
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'
